services:
  - type: web
    name: resolve-backend
    env: docker
    plan: free
    dockerImage: kavidoi/resolve-backend:latest
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: "${MONGODB_URI}"
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
      - key: JWT_EXPIRES_IN
        value: "${JWT_EXPIRES_IN}"
      - key: CORS_ORIGIN
        value: "https://resolve-xb6d.onrender.com"

  - type: web
    name: resolve-frontend-docker
    env: docker
    plan: free
    dockerImage: kavidoi/resolve-frontend:latest
    autoDeploy: true