services:
  - type: web
    runtime: static
    name: resolve-frontend
    branch: main
    rootDir: front-end
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    plan: free
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: resolve-backend
    runtime: java
    branch: main
    rootDir: back-end/resolve-backend
    buildCommand: mvn clean package
    startCommand: java -jar target/resolve-backend-1.0-SNAPSHOT.jar --server.port=$PORT
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: MONGODB_URI
        value: "${MONGODB_URI}"
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
      - key: JWT_EXPIRES_IN
        value: "${JWT_EXPIRES_IN}"
      - key: CORS_ORIGIN
        value: "https://re-solve.onrender.com"