services:
  # Frontend static site
  - type: web
    runtime: static
    name: resolve-frontend
    branch: main
    rootDir: front-end
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production

  # Backend Docker-based service
  - type: web
    runtime: docker
    name: resolve-backend
    branch: main
    dockerfilePath: back-end/Dockerfile
    dockerContext: back-end
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false
      - key: CORS_ORIGIN
        value: "https://resolve-frontend-n6tj.onrender.com"
      - key: PORT
        value: 10000