services:
  - type: web
    name: resolve-backend
    env: node
    plan: free
    branch: main
    buildCommand: |
      cd back-end
      npm install
    startCommand: |
      cd back-end
      npm start
    envVars:
      - key: MONGODB_URI
        value: "${MONGODB_URI}"
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
      - key: JWT_EXPIRES_IN
        value: "${JWT_EXPIRES_IN}"
      - key: CORS_ORIGIN
        value: "https://resolve-xb6d.onrender.com"

  - type: static_site
    name: resolve-frontend
    env: static
    plan: free
    branch: main
    buildCommand: |
      cd front-end
      npm install
      npm run build
    publishDirectory: front-end/dist 