services:
  - type: web
    runtime: static
    name: resolve-frontend
    branch: main
    rootDir: front-end
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: resolve-backend
    runtime: docker
    branch: main
    rootDir: back-end/resolve-backend
    buildCommand: mvn clean package
    plan: starter
    healthCheckPath: /healthz
    envVars:
      - key: MONGODB_URI
        value: "${MONGODB_URI}"
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
      - key: JWT_EXPIRES_IN
        value: "${JWT_EXPIRES_IN}"
      - key: CORS_ORIGIN
        value: "https://re-solve.onrender.com"