services:
  # Frontend static site
  - type: web
    runtime: static
    name: resolve-frontend
    branch: main
    rootDir: front-end
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production

  # Backend Docker-based service
  - type: web
    runtime: docker
    name: resolve-backend
    branch: main
    rootDir: back-end/resolve-backend
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: starter
    healthCheckPath: /healthz
    envVars:
      - key: MONGODB_URI
        value: "${MONGODB_URI}"
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
      - key: JWT_EXPIRES_IN
        value: "${JWT_EXPIRES_IN}"
      - key: CORS_ORIGIN
        value: "https://re-solve.onrender.com"